// src/lib/planes.ts — Planes y excursiones por cantón

export type TipoActividad = "senderismo" | "teleferico" | "esqui" | "lago" | "cultura" | "gastronomia" | "urbano" | "nieve" | "naturaleza" | "ciclismo" | "familia";
export type Dificultad = "facil" | "moderada" | "dificil" | "muy-dificil";
export type Temporada = "primavera" | "verano" | "otono" | "invierno";

export type Actividad = {
  slug: string;
  nombre: string;
  tipo: TipoActividad;
  descripcion: string;
  dificultad?: Dificultad;
  duracion?: string;
  distancia?: string;
  desnivel?: string;
  altitud?: string;
  precio?: string;
  gratuito?: boolean;
  temporada: Temporada[];
  destacado: boolean;
  imagen: string;
  comoLlegar: string;
  consejos: string[];
  cercaDe: string;
  keywords: string[];
  coordenadas?: { lat: number; lng: number };
  aptoNinos?: boolean;
  aptoPerros?: boolean;
  equipamiento?: string[];
  urlSBB?: string;
};

export type Canton = {
  slug: string;
  nombre: string;
  region: "alemana" | "francesa" | "italiana" | "romanche";
  descripcion: string;
  imagen: string;
  coordenadas?: { lat: number; lng: number };
  actividades: Actividad[];
};

const cantones: Canton[] = [
  // ── VALAIS ────────────────────────────────────────────────────────────────
  {
    slug: "valais",
    nombre: "Valais",
    region: "francesa",
    descripcion: "El cantón más montañoso de Suiza, hogar del Matterhorn y Zermatt. Imprescindible para esquí, senderismo alpino y los mejores vinos suizos.",
    imagen: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "matterhorn-glaciar-paradise",
        nombre: "Matterhorn Glacier Paradise",
        tipo: "teleferico",
        descripcion: "El teleférico más alto de Europa (3.883m) con vistas al Matterhorn y glaciar Klein Matterhorn.",
        duracion: "Día completo",
        precio: "106 CHF adulto (ida y vuelta)",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: true,
        dificultad: "facil",
        imagen: "https://images.unsplash.com/photo-1743363801082-5a6102531a8d?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren desde Brig o Visp hasta Zermatt (sin coches). Desde Zermatt, teleférico en el centro del pueblo.",
        consejos: [
          "Reserva online con antelación en verano: la cola puede superar 2 horas.",
          "Lleva ropa de abrigo aunque sea verano: en la cumbre hace frío intenso.",
          "El forfait Zermatt Peak Pass incluye todos los teleféricos del área.",
          "La cueva de hielo está incluida en el precio del teleférico.",
        ],
        cercaDe: "Zermatt, 0 km",
        keywords: ["matterhorn teleférico", "glacier paradise zermatt", "teleférico más alto europa", "zermatt precio"],
      },
      {
        slug: "ruta-alta-via-valais",
        nombre: "Haute Route Zermatt–Saas-Fee",
        tipo: "senderismo",
        descripcion: "Una de las rutas de alta montaña más espectaculares de los Alpes, entre glaciares y cumbres de más de 4.000m.",
        dificultad: "muy-dificil",
        duracion: "7-10 días",
        distancia: "120 km",
        desnivel: "+8.000m",
        temporada: ["verano"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1458668383970-8ddd3927deed?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Inicio en Zermatt (tren desde Visp/Brig). Final en Saas-Fee (autobús desde Visp).",
        consejos: [
          "Reserva refugios con meses de antelación; se llenan enseguida en julio y agosto.",
          "Imprescindible experiencia en nieve/glaciar y crampones/piolet.",
          "Contrata un guía de montaña certificado para los tramos glaciares.",
          "Infórmate del estado del tiempo: la ruta tiene partes expuestas.",
        ],
        cercaDe: "Zermatt, inicio",
        keywords: ["haute route valais senderismo", "ruta alta zermatt saas-fee", "senderismo alta montaña suiza"],
      },
      {
        slug: "esqui-verbier",
        nombre: "Esquí en Verbier (4 Vallées)",
        tipo: "esqui",
        descripcion: "Una de las estaciones de esquí más grandes de Europa con más de 400 km de pistas en los 4 Vallées.",
        duracion: "Día completo",
        precio: "Forfait día 85-95 CHF adulto",
        temporada: ["invierno"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Autobús desde Martigny (estación de tren). O tren hasta Le Châble y telecabina hasta Verbier.",
        consejos: [
          "Reserva forfait online: hasta 20% de descuento frente al precio en ventanilla.",
          "En temporada alta (Navidad, febrero) reserva clases de esquí con semanas de antelación.",
          "El Mont-Fort (3.330m) es el punto más alto y el más demandado.",
          "Prueba los restaurantes de montaña: la raclette en Le Rouge es imprescindible.",
        ],
        cercaDe: "Martigny, 30 km",
        keywords: ["verbier esqui precio forfait", "4 vallées suiza esqui", "estacion esqui verbier"],
      },
      {
        slug: "gorge-de-baltschieder",
        nombre: "Garganta de Baltschieder",
        tipo: "senderismo",
        descripcion: "Impresionante cañón escondido cerca de Visp con caminos tallados en la roca y saltos de agua.",
        dificultad: "moderada",
        duracion: "3-4 horas",
        distancia: "8 km",
        precio: "Gratis",
        temporada: ["primavera", "verano", "otono"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Visp, luego autobús al pueblo de Baltschieder (15 min).",
        consejos: [
          "Lleva calzado de trekking con buena suela antideslizante.",
          "Algunos tramos tienen cuerdas de seguridad: presta atención.",
          "Ideal para un día de entre semana para evitar aglomeraciones.",
        ],
        cercaDe: "Visp, 5 km",
        keywords: ["garganta baltschieder valais", "cañón suiza excursión", "rutas senderismo visp"],
      },
      {
        slug: "lago-derborence",
        nombre: "Lago de Derborence",
        tipo: "lago",
        descripcion: "Lago de origen glaciar en un paraje casi virgen, formado por un deslizamiento de tierra en 1749.",
        dificultad: "moderada",
        duracion: "4-5 horas",
        distancia: "10 km",
        precio: "Gratis",
        temporada: ["primavera", "verano", "otono"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1761845359334-9866fb7f23e1?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Autobús desde Sion hasta Derborence (temporada estival). O coche desde Conthey.",
        consejos: [
          "El acceso en autobús es limitado: consulta horarios con antelación.",
          "Zona de reserva natural: no está permitido acampar ni hacer fuego.",
          "Los pinos del lago son de los más antiguos de Suiza.",
        ],
        cercaDe: "Sion, 25 km",
        keywords: ["lago derborence valais", "lago glaciar suiza", "senderismo sion valais"],
      },
      {
        slug: "viñedos-sion",
        nombre: "Ruta del vino en Sion",
        tipo: "gastronomia",
        descripcion: "Los viñedos más altos de Europa producen el famoso Fendant y Dôle. Paseo entre bodegas centenarias.",
        dificultad: "facil",
        duracion: "2-3 horas",
        precio: "Cata desde 20 CHF",
        temporada: ["primavera", "verano", "otono"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1474722883778-792e7990302f?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren directo a Sion desde Lausana (1h) o desde Brig (45 min).",
        consejos: [
          "La cosecha es en septiembre/octubre: la época más animada del año.",
          "Reserva catas en las bodegas con antelación en temporada alta.",
          "Combina la visita con el Château de Valère y Tourbillon, que dominan la ciudad.",
        ],
        cercaDe: "Sion, centro",
        keywords: ["vino valais sion", "bodegas suiza visita", "fendant vino suizo", "ruta del vino sion"],
      },
      {
        slug: "saas-fee-glacier",
        nombre: "Saas-Fee: el pueblo glaciar",
        tipo: "teleferico",
        descripcion: "Pueblo sin coches rodeado de 13 cumbres de más de 4.000m. Teleférico hasta el glaciar Felskinn (3.000m).",
        dificultad: "facil",
        duracion: "Día completo",
        precio: "Felskinn teleférico 55 CHF ida/vuelta",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1660460373717-b34e8260705e?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Autobús PostAuto desde Visp (estación tren) hasta Saas-Fee (1h). Aparca en Saas-Almagell si vas en coche.",
        consejos: [
          "Saas-Fee es completamente peatonal: deja el coche en el aparcamiento de entrada.",
          "El metro alpino subterráneo (Alpin Express) conecta el glaciar con la zona de esquí.",
          "En verano hay esquí glaciar incluso en julio y agosto.",
        ],
        cercaDe: "Visp, 30 km",
        keywords: ["saas-fee glaciar teleférico", "pueblo sin coches suiza", "esqui verano saas-fee"],
      },
      {
        slug: "zermatt-esqui-cervino",
        nombre: "Esquí en Zermatt con vistas al Matterhorn",
        tipo: "esqui",
        descripcion: "360 km de pistas con el Matterhorn como telón de fondo. Esquí garantizado todo el año gracias al glaciar Klein Matterhorn.",
        duracion: "Día completo",
        precio: "Forfait diario 95-110 CHF adulto",
        temporada: ["invierno", "verano"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren Matterhon Gotthard Bahn desde Brig hasta Zermatt (sin coches).",
        consejos: [
          "El forfait Zermatt Peak Pass es el más completo e incluye el Glacier Paradise.",
          "La pista Nationale (8 km de descenso) es imprescindible para esquiadores intermedios.",
          "Reserva alojamiento con meses de antelación: Zermatt se llena rápido.",
        ],
        cercaDe: "Brig, 1h en tren",
        keywords: ["zermatt esqui forfait precio", "pistas esqui zermatt", "matterhorn esqui"],
      },
    ],
  },

  // ── BERNA ──────────────────────────────────────────────────────────────────
  {
    slug: "berna",
    nombre: "Berna",
    region: "alemana",
    descripcion: "Capital federal de Suiza con el impresionante Oberland bernés: Jungfrau, Eiger, Mönch y los lagos de Thun e Interlaken.",
    imagen: "https://images.unsplash.com/photo-1741900033774-5957b5f03dd7?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "jungfraujoch-top-of-europe",
        nombre: "Jungfraujoch — Top of Europe (3.454m)",
        tipo: "teleferico",
        descripcion: "La estación de tren más alta de Europa, con vistas al glaciar Aletsch y las cumbres del Oberland bernés.",
        dificultad: "facil",
        duracion: "Día completo",
        precio: "Desde 162 CHF adulto (Swiss Travel Pass descuento 50%)",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1491555103944-7c647fd857e6?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Interlaken Ost o Grindelwald, luego tren de montaña Jungfraubahn. Desde Zúrich ~2,5h.",
        consejos: [
          "Compra el billete online: hay tarifas Good Morning (primera salida) más baratas.",
          "Lleva ropa de abrigo muy abrigada aunque sea verano: -10°C en la cumbre.",
          "La mejor vista al glaciar Aletsch es desde la terraza Sphinx.",
          "Con Swiss Travel Pass pagas solo el 50% del trayecto desde Interlaken.",
        ],
        cercaDe: "Interlaken, 1,5h en tren de montaña",
        keywords: ["jungfraujoch precio billete", "top of europe suiza", "tren montaña jungfrau"],
      },
      {
        slug: "lago-thun-brienz",
        nombre: "Lagos de Thun y Brienz en barco",
        tipo: "lago",
        descripcion: "Crucero panorámico por dos de los lagos más bellos de Suiza con vistas a los Alpes del Oberland bernés.",
        dificultad: "facil",
        duracion: "4-6 horas (circuito completo)",
        precio: "Swiss Travel Pass: incluido. Sin tarjeta: ~30 CHF",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Interlaken West (lago Thun) o Interlaken Ost (lago Brienz). Embarcaderos junto a las estaciones.",
        consejos: [
          "Con Swiss Travel Pass el barco está incluido sin coste adicional.",
          "Brienz es famosa por sus tallistas de madera: visita el taller del pueblo.",
          "La cascada de Giessbach, junto al lago Brienz, es accesible desde el barco.",
          "En verano hay hasta 10 salidas diarias en cada lago.",
        ],
        cercaDe: "Interlaken, centro",
        keywords: ["lago thun barco excursion", "lago brienz suiza", "interlaken crucero precio"],
      },
      {
        slug: "harder-kulm-interlaken",
        nombre: "Harder Kulm (1.322m) — Balcón de Interlaken",
        tipo: "teleferico",
        descripcion: "Teleférico en 8 minutos hasta el mirador con vistas simultáneas a los lagos Thun y Brienz y las cumbres alpinas.",
        dificultad: "facil",
        duracion: "2-3 horas",
        precio: "32 CHF ida/vuelta (Swiss Travel Pass 50%)",
        temporada: ["primavera", "verano", "otono"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "A pie desde la estación de Interlaken Ost (5 min), estación del funicular al lado del puente sobre el Aare.",
        consejos: [
          "Es la mejor vista de Interlaken sin tener que caminar.",
          "El restaurante Harder Kulm tiene terraza con panorama a los tres lagos.",
          "Combina bien con el barco por el lago Brienz el mismo día.",
        ],
        cercaDe: "Interlaken, 0,5 km",
        keywords: ["harder kulm teleférico interlaken", "mirador interlaken precio", "vistas lago thun brienz"],
      },
      {
        slug: "eiger-trail-grindelwald",
        nombre: "Eiger Trail — Sendero bajo la Cara Norte",
        tipo: "senderismo",
        descripcion: "Ruta junto a la mítica cara norte del Eiger, con vistas cercanas a la pared que desafió a generaciones de alpinistas.",
        dificultad: "moderada",
        duracion: "4-5 horas",
        distancia: "9,7 km",
        desnivel: "-750m",
        temporada: ["verano", "otono"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren Jungfraubahn desde Grindelwald hasta Eigergletscher (incluido en billete Jungfraujoch o tarifa reducida).",
        consejos: [
          "Inicio en Eigergletscher (2.300m), descenso hacia Grindelwald.",
          "La cara norte es una de las más filmadas del alpinismo: impresionante de cerca.",
          "Calzado de trekking con suela sólida imprescindible.",
        ],
        cercaDe: "Grindelwald, destino final",
        keywords: ["eiger trail grindelwald senderismo", "cara norte eiger ruta", "senderismo grindelwald"],
      },
      {
        slug: "esqui-grindelwald-wengen",
        nombre: "Esquí en Grindelwald-Wengen (Jungfrau Ski Region)",
        tipo: "esqui",
        descripcion: "200 km de pistas conectadas entre Grindelwald, Wengen y Mürren con el espectacular paisaje del Eiger-Mönch-Jungfrau.",
        duracion: "Día completo",
        precio: "Forfait diario 79-92 CHF adulto",
        temporada: ["invierno"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1516802273409-68526ee1bdd6?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Grindelwald o Lauterbrunnen, luego telecabinas hasta las pistas.",
        consejos: [
          "La pista Lauberhorn (Wengen) es famosa por el descenso de Copa del Mundo.",
          "Mürren es un pueblo sin coches: ambiente tranquilo y familiar.",
          "Los pases de semana son más económicos que días sueltos.",
        ],
        cercaDe: "Interlaken, 20 km",
        keywords: ["grindelwald esqui forfait precio", "jungfrau ski region", "wengen esqui suiza"],
      },
      {
        slug: "ciudad-berna-historica",
        nombre: "Berna: Zytglogge y la Ciudad Vieja UNESCO",
        tipo: "cultura",
        descripcion: "Pasea por los 6 km de arcadas medievales de la capital suiza, declarada Patrimonio de la Humanidad por la UNESCO.",
        dificultad: "facil",
        duracion: "3-4 horas",
        precio: "Gratis (museo Zytglogge 8 CHF)",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1555993539-1732b0258235?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren directo a Berna desde Zúrich (1h), Ginebra (1h45) o Basilea (55 min).",
        consejos: [
          "El reloj Zytglogge da el espectáculo de los autómatas 4 minutos antes de cada hora.",
          "La Rosengarten ofrece las mejores vistas a los tejados de la Ciudad Vieja.",
          "Los osos (símbolo de Berna) viven en el Bärenpark junto al río Aare.",
          "El Foso de los Osos es gratuito y abre todos los días.",
        ],
        cercaDe: "Berna, centro",
        keywords: ["berna ciudad vieja visita", "zytglogge berna", "capital suiza turismo", "berna patrimonio humanidad"],
      },
      {
        slug: "cascadas-trummelbach",
        nombre: "Cataratas de Trümmelbach (dentro de la roca)",
        tipo: "naturaleza",
        descripcion: "Las únicas cataratas glaciares intra-montaña del mundo, con 20.000 litros/segundo desaguando dentro de la roca.",
        dificultad: "facil",
        duracion: "1,5 horas",
        precio: "14 CHF adulto",
        temporada: ["primavera", "verano", "otono"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Autobús desde Lauterbrunnen (10 min). Lauterbrunnen en tren desde Interlaken (20 min).",
        consejos: [
          "El ascensor interno te lleva hasta la catarata más alta.",
          "En primavera el caudal es máximo: espectacular pero muy ruidoso.",
          "Combina con la cascada Staubbachfall en el pueblo de Lauterbrunnen (gratuita).",
        ],
        cercaDe: "Lauterbrunnen, 3 km",
        keywords: ["cataratas trummelbach lauterbrunnen", "cascadas glaciares suiza", "lauterbrunnen excursión"],
      },
      {
        slug: "niederhorn-beatenberg",
        nombre: "Niederhorn (1.963m) — Mirador sobre el lago Thun",
        tipo: "teleferico",
        descripcion: "Teleférico desde Beatenberg con panorama a 360° sobre el lago Thun, Eiger, Mönch y Jungfrau.",
        dificultad: "facil",
        duracion: "Medio día",
        precio: "40 CHF ida/vuelta",
        temporada: ["primavera", "verano", "otono"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Barco desde Interlaken hasta Beatenbucht, luego funicular hasta Beatenberg y telecabina al Niederhorn.",
        consejos: [
          "La combinación barco + funicular + telecabina está incluida en el Swiss Travel Pass.",
          "Hay senderos de fácil acceso en la cima aptos para familias con niños.",
        ],
        cercaDe: "Interlaken, 30 min en barco + funicular",
        keywords: ["niederhorn beatenberg teleférico", "mirador lago thun", "senderismo oberland bernés"],
      },
    ],
  },

  // ── GRISONES ──────────────────────────────────────────────────────────────
  {
    slug: "grisones",
    nombre: "Grisones",
    region: "romanche",
    descripcion: "El cantón más grande de Suiza con tres idiomas oficiales, el Parque Nacional Suizo, Davos y los lujosos deportes de invierno de St. Moritz.",
    imagen: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "esqui-st-moritz",
        nombre: "Esquí en St. Moritz — Upper Engadin",
        tipo: "esqui",
        descripcion: "El destino de esquí más glamuroso del mundo, con 350 km de pistas y el famoso sol del Engadina.",
        duracion: "Día completo",
        precio: "Forfait diario 90-105 CHF adulto",
        temporada: ["invierno"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1487708289540-59cc11e9452c?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Glacier Express desde Zermatt (7h45) o tren Intercity desde Zúrich (3h15).",
        consejos: [
          "El forfait Engadin St. Moritz Mountain incluye todas las estaciones del área.",
          "Corviglia y Corvatsch son los sectores más famosos para esquiadores avanzados.",
          "En enero es el Polo World Cup sobre el lago helado: espectáculo único.",
        ],
        cercaDe: "St. Moritz, centro",
        keywords: ["st moritz esqui forfait precio", "pistas esqui engadina", "st moritz vacaciones esqui"],
      },
      {
        slug: "glacier-express",
        nombre: "Glacier Express: Zermatt–St. Moritz",
        tipo: "cultura",
        descripcion: "El tren panorámico más famoso del mundo cruza 291 puentes y 91 túneles a través de los Alpes suizos en 8 horas.",
        dificultad: "facil",
        duracion: "8 horas (trayecto completo)",
        precio: "Reserva 39 CHF + billete (Swiss Travel Pass válido)",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1478827217976-7214a0556393?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Sale de Zermatt y llega a St. Moritz, o viceversa. Reserva el asiento online.",
        consejos: [
          "Los asientos del lado derecho (sentido Zermatt→St.Moritz) tienen las mejores vistas.",
          "El desayuno o almuerzo a bordo es caro pero la experiencia merece la pena.",
          "En invierno el paisaje nevado es especialmente fotogénico.",
          "Hay servicio Excellence Class con techo panorámico completo.",
        ],
        cercaDe: "Trayecto entre Valais y Grisones",
        keywords: ["glacier express precio reserva", "tren panorámico suiza", "zermatt st moritz tren"],
      },
      {
        slug: "parque-nacional-suizo",
        nombre: "Parque Nacional Suizo (Engadina)",
        tipo: "naturaleza",
        descripcion: "El único parque nacional de Suiza, totalmente virgen desde 1914. Avistamiento de ciervos, marmotas y águilas reales.",
        dificultad: "moderada",
        duracion: "Día completo",
        precio: "Gratis (acceso libre)",
        temporada: ["verano", "otono"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Autobús PostAuto desde Zernez (estación de tren Engadina) hasta las distintas entradas del parque.",
        consejos: [
          "Está completamente prohibido salirse de los senderos marcados.",
          "Al amanecer y atardecer hay más probabilidad de ver ciervos y gamuzas.",
          "El centro de visitantes en Zernez tiene mapas detallados de rutas.",
          "Julio y agosto son los mejores meses para avistamiento de fauna.",
        ],
        cercaDe: "Zernez, 0 km",
        keywords: ["parque nacional suizo engadina", "flora fauna suiza parque", "zernez senderismo naturaleza"],
      },
      {
        slug: "davos-esqui-parsenn",
        nombre: "Davos-Klosters: Parsenn y Jakobshorn",
        tipo: "esqui",
        descripcion: "La zona esquiable más grande de los Grisones con el famoso descenso Parsenn y 320 km de pistas.",
        duracion: "Día completo",
        precio: "Forfait diario 78-88 CHF adulto",
        temporada: ["invierno"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren directo desde Zúrich a Davos (2h15) con el tren panorámico Rätische Bahn.",
        consejos: [
          "El Parsenn tiene la bajada más larga de Suiza (12 km hasta Küblis).",
          "Jakobshorn es el sector snowboard/freeski más animado.",
          "En enero coincide con el Foro Económico Mundial: el pueblo se llena.",
        ],
        cercaDe: "Davos, centro",
        keywords: ["davos esqui pistas klosters", "parsenn descenso suiza", "forfait davos precio"],
      },
      {
        slug: "via-mala",
        nombre: "Desfiladero Via Mala",
        tipo: "naturaleza",
        descripcion: "Espectacular garganta labrada por el río Hinterrhein con paredes de 300m que forman la ruta romana más antigua de los Alpes.",
        dificultad: "facil",
        duracion: "2 horas",
        precio: "5 CHF adulto",
        temporada: ["primavera", "verano", "otono"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Autobús o coche desde Thusis (A13, salida Thusis). A 30 min al sur de Coira.",
        consejos: [
          "Los puentes sobre el precipicio generan vértigo: no apto para acrofóbicos.",
          "Mejor visitarla en primavera/verano cuando el río baja con más caudal.",
          "Hay pasarelas y miradores a varios niveles con acceso para familias.",
        ],
        cercaDe: "Thusis, 5 km",
        keywords: ["via mala desfiladero grisones", "garganta via mala excursion", "thusis senderismo"],
      },
      {
        slug: "laax-esqui-freestyle",
        nombre: "Laax — Capital del Freestyle",
        tipo: "esqui",
        descripcion: "Estación líder en snowboard y freestyle con el mayor halfpipe del mundo y 224 km de pistas.",
        duracion: "Día completo",
        precio: "Forfait diario 72-82 CHF adulto",
        temporada: ["invierno"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Autobús directo desde Zúrich hasta Flims-Laax (2h) o desde Coira en 45 min.",
        consejos: [
          "El Freestyle.ch contest (febrero) es uno de los eventos de nieve más espectaculares.",
          "La aldea de Flims tiene un bonito lago para patinar en invierno.",
          "Hay park para principiantes y área de iniciación muy bien señalizada.",
        ],
        cercaDe: "Coira, 40 km",
        keywords: ["laax esqui snowboard suiza", "flims laax pistas precio", "freestyle suiza snowboard"],
      },
    ],
  },

  // ── TICINO ────────────────────────────────────────────────────────────────
  {
    slug: "ticino",
    nombre: "Ticino",
    region: "italiana",
    descripcion: "El cantón italiano de Suiza con lagos como Lugano, Maggiore y Como, palmeras y el sabor mediterráneo de la Confederación.",
    imagen: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "lugano-lago-monte-bre",
        nombre: "Lago Lugano: barco y Monte Brè",
        tipo: "lago",
        descripcion: "Crucero por el lago Lugano hasta los pueblos de Gandria y Morcote, con opción de subir al Monte Brè en funicular.",
        dificultad: "facil",
        duracion: "Día completo",
        precio: "Barco: Swiss Travel Pass incluido. Monte Brè: 22 CHF",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Lugano (2h desde Zúrich, 3h desde Ginebra). Embarcadero junto a la estación del funicular.",
        consejos: [
          "Gandria es un pueblo medieval sin coches accesible solo en barco o a pie.",
          "Monte Brè es el monte más soleado de Suiza: brilla casi 2.300 horas al año.",
          "La Via Verde (senderismo litoral) rodea el lago con paisajes mediterráneos.",
        ],
        cercaDe: "Lugano, centro",
        keywords: ["lago lugano barco excursion", "gandria suiza visita", "lugano monte bre teleférico"],
      },
      {
        slug: "lago-maggiore-ascona",
        nombre: "Lago Maggiore: Ascona y las Isole di Brissago",
        tipo: "lago",
        descripcion: "Paseo por el pintoresco puerto de Ascona y crucero a las islas Brissago con jardín botánico subtropical.",
        dificultad: "facil",
        duracion: "Día completo",
        precio: "Barco Ascona-Brissago: 18 CHF. Jardín: 10 CHF",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Locarno, luego bus o barco hasta Ascona (20 min).",
        consejos: [
          "Las Isole di Brissago tienen el único jardín botánico subtropical de Suiza.",
          "Ascona tiene el paseo lacustre más bonito del Ticino.",
          "El mercado semanal del jueves en Locarno es muy animado.",
        ],
        cercaDe: "Locarno, 4 km",
        keywords: ["lago maggiore ascona suiza", "isole brissago visita", "locarno lago excursion"],
      },
      {
        slug: "valle-verzasca",
        nombre: "Valle Verzasca: el paraíso del agua turquesa",
        tipo: "naturaleza",
        descripcion: "Río de agua cristalina con piscinas naturales turquesas para bañarse, el puente romano Ponte dei Salti y salto de bungee de la presa.",
        dificultad: "facil",
        duracion: "Día completo",
        precio: "Gratis (bungee: 255 CHF)",
        temporada: ["verano"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Autobús desde Locarno hasta Lavertezzo (1h). Paradas en varios puntos del valle.",
        consejos: [
          "La piscina natural de Lavertezzo es la más fotografiada del valle.",
          "Evita la primera semana de agosto: saturación máxima.",
          "El bungee de la presa de Contra (220m) es uno de los saltos más icónicos del mundo (007 GoldenEye).",
          "Llevar calzado con suela antideslizante para caminar sobre las rocas.",
        ],
        cercaDe: "Locarno, 30 km",
        keywords: ["verzasca valle ticino suiza", "agua turquesa suiza bañarse", "lavertezzo piscinas naturales"],
      },
      {
        slug: "cimetta-cardada-locarno",
        nombre: "Cardada-Cimetta: mirador sobre el lago Maggiore",
        tipo: "teleferico",
        descripcion: "Telecabina desde Locarno hasta Cardada y Cimetta con vistas panorámicas al lago Maggiore y los Alpes.",
        dificultad: "facil",
        duracion: "Medio día",
        precio: "38 CHF ida/vuelta (Swiss Travel Pass 50%)",
        temporada: ["primavera", "verano", "otono"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1665125688197-7318b9b86dc4?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "La telecabina parte del Orselina, a 5 min en funicular desde Locarno.",
        consejos: [
          "El funicular hasta Orselina ya incluye vistas bonitas al lago.",
          "Cimetta (1.670m) tiene un parque de aventura y senderos aptos para familias.",
          "En días claros se ve hasta el lago de Como en Italia.",
        ],
        cercaDe: "Locarno, 0,5 km",
        keywords: ["cardada cimetta teleférico locarno", "mirador lago maggiore suiza", "locarno telecabina precio"],
      },
      {
        slug: "lugano-ciudad-cultura",
        nombre: "Lugano: Arte y gastronomía italiana",
        tipo: "cultura",
        descripcion: "Pasea por el barrio viejo de Lugano, el LAC (museo de arte) y disfruta de la gastronomía italiana del Ticino.",
        dificultad: "facil",
        duracion: "3-4 horas",
        precio: "LAC museo: 15 CHF",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Lugano desde Zúrich (2h), Bellinzona (30 min) o Milán (1h15).",
        consejos: [
          "El LAC (Lugano Arte e Cultura) tiene exposiciones temporales de primer nivel.",
          "Las callejuelas del barrio viejo con restaurantes de risotto y pasta son la esencia del Ticino.",
          "El mercado del sábado en la piazza es colorido y lleno de productos locales.",
        ],
        cercaDe: "Lugano, centro",
        keywords: ["lugano visita turismo", "arte cultura lugano suiza", "que hacer lugano"],
      },
    ],
  },

  // ── ZÚRICH ────────────────────────────────────────────────────────────────
  {
    slug: "zurich",
    nombre: "Zúrich",
    region: "alemana",
    descripcion: "La mayor ciudad suiza combina la elegancia financiera con el lago Zúrich, la cadena montañosa del Albis y acceso rápido a los Alpes.",
    imagen: "https://images.unsplash.com/photo-1742626301055-a140b7cfad6b?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "uetliberg-mirador-zurich",
        nombre: "Uetliberg (870m) — El Balcón de Zúrich",
        tipo: "senderismo",
        descripcion: "El mirador más accesible de Zúrich en tren directo desde la ciudad, con vistas al lago y los Alpes.",
        dificultad: "facil",
        duracion: "2-3 horas",
        precio: "Incluido en abono de zona o Swiss Travel Pass",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1531743579253-fa8d52993ba5?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Línea S10 desde Zúrich HB (Hauptbahnhof) hasta estación Uetliberg (25 min).",
        consejos: [
          "La cresta de la montaña (Planetenweg) conecta Uetliberg con Felsenegg: 5 km de paseo espectacular.",
          "Con nieve es especialmente fotogénico, pero lleva calzado adecuado.",
          "El restaurante en la cumbre tiene terraza con vistas al lago.",
          "Al atardecer con niebla baja sobre la ciudad, las vistas son extraordinarias.",
        ],
        cercaDe: "Zúrich, 15 km",
        keywords: ["uetliberg zurich excursion", "mirador zurich lago", "senderismo zurich día"],
      },
      {
        slug: "lago-zurich-bano",
        nombre: "Lago Zürich: Bañarse en las Badi",
        tipo: "lago",
        descripcion: "Las piscinas fluviales públicas (Badi) son la institución veraniega de Zúrich: baño en el lago con trampolines y bar.",
        dificultad: "facil",
        duracion: "Medio día",
        precio: "Badi: 8 CHF aprox.",
        temporada: ["verano"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1742105682489-94149abb1009?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tram o tranvía desde el centro. La Badi más famosa es la Seebad Enge o la Strandbad Tiefenbrunnen.",
        consejos: [
          "Las Badi abren de mediados de mayo a mediados de septiembre.",
          "Algunas son solo para mujeres (Frauenbadi): espacios tranquilos y sauna flotante.",
          "Llega antes de las 10h en verano para conseguir sitio.",
          "El agua del lago Zürich es potable y de excelente calidad.",
        ],
        cercaDe: "Zúrich, orillas del lago",
        keywords: ["lago zurich bañarse badi", "piscinas naturales zurich", "lago zurich precio"],
      },
      {
        slug: "zurich-altstadt",
        nombre: "Altstadt de Zúrich y Grossmünster",
        tipo: "cultura",
        descripcion: "Paseo por la ciudad vieja con el Grossmünster, Fraumünster (vidrieras de Chagall) y Niederdorf.",
        dificultad: "facil",
        duracion: "3-4 horas",
        precio: "Gratis (torres Grossmünster: 5 CHF)",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1752118396172-20f9f3098a2c?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren a Zúrich HB, luego a pie por la Bahnhofstrasse cruzando el río Limmat.",
        consejos: [
          "Las vidrieras de Marc Chagall en el Fraumünster son únicas: visita gratuita pero donación voluntaria.",
          "El barrio Niederdorf tiene los mejores bares y restaurantes de la ciudad vieja.",
          "Sube a las torres del Grossmünster para la mejor vista de la ciudad.",
        ],
        cercaDe: "Zúrich, centro",
        keywords: ["zurich ciudad vieja visita", "grossmunster zurich", "fraumunster chagall zurich"],
      },
      {
        slug: "rapperswil-lago-zurich",
        nombre: "Rapperswil y el lago Zúrich en tren y barco",
        tipo: "lago",
        descripcion: "La ciudad de las rosas en el extremo del lago Zürich: castillo medieval, puerto y barco de vuelta.",
        dificultad: "facil",
        duracion: "Día completo",
        precio: "Swiss Travel Pass incluido",
        temporada: ["primavera", "verano", "otono"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1530062063719-e2d6fe70d7b8?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "S-Bahn desde Zúrich HB hasta Rapperswil (45 min). Regreso en barco (2h).",
        consejos: [
          "El barco de vuelta es panorámico y muy cómodo en verano.",
          "El castillo medieval de Rapperswil tiene vistas espectaculares al lago.",
          "En mayo y junio el jardín de rosas está en plena floración.",
        ],
        cercaDe: "Zúrich, 45 km",
        keywords: ["rapperswil zurich barco excursion", "castillo rapperswil visita", "lago zurich barco"],
      },
    ],
  },

  // ── VAUD ──────────────────────────────────────────────────────────────────
  {
    slug: "vaud",
    nombre: "Vaud",
    region: "francesa",
    descripcion: "Viñedos Patrimonio de la Humanidad, el lago Lemán y Lausana, el Olympism con el CIO, y las estaciones de esquí de Leysin y Les Diablerets.",
    imagen: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "vinedos-lavaux-barco",
        nombre: "Viñedos de Lavaux (UNESCO) y barco por el Lemán",
        tipo: "naturaleza",
        descripcion: "Paseo entre viñedos en terrazas con 1.000 años de historia sobre el lago Lemán, Patrimonio de la Humanidad.",
        dificultad: "facil",
        duracion: "Medio día",
        precio: "Gratis (barco: Swiss Travel Pass incluido)",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Lutry o Grandvaux (15 min desde Lausana). El sendero de los viñedos está señalizado.",
        consejos: [
          "La ruta más bonita va de Rivaz a Cully (5 km, fácil).",
          "En septiembre durante la vendimia se puede participar en la cosecha.",
          "Cata de Chasselas en las bodegas locales: el vino blanco por excelencia del Lemán.",
          "El barco de regreso a Lausana cierra el día perfectamente.",
        ],
        cercaDe: "Lausana, 15 km",
        keywords: ["lavaux viñedos suiza patrimonio", "ruta viñedos lausana", "chasselas vino vaud"],
      },
      {
        slug: "castillo-chillon",
        nombre: "Castillo de Chillon",
        tipo: "cultura",
        descripcion: "El castillo medieval más visitado de Suiza, junto al lago Lemán, inmortalizado por Lord Byron.",
        dificultad: "facil",
        duracion: "2-3 horas",
        precio: "13 CHF adulto",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1488085061387-422e29b40080?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Veytaux-Chillon o barco desde Montreux (10 min). Desde Montreux a pie por el lago (45 min).",
        consejos: [
          "La mazmorra donde estuvo prisionero Bonivard inspiró el poema de Byron.",
          "Combina bien con Montreux y el paseo de los Narcisos en primavera.",
          "La vista del castillo desde el lago al amanecer es de las más fotografiadas de Suiza.",
        ],
        cercaDe: "Montreux, 3 km",
        keywords: ["castillo chillon suiza precio", "montreux lago leman visita", "chillon medieval suiza"],
      },
      {
        slug: "leysin-esqui-las-diablerets",
        nombre: "Les Diablerets y Glacier 3000",
        tipo: "esqui",
        descripcion: "Estación glaciar accesible en bus desde Gstaad o Les Diablerets con 623 ha de nieve garantizada.",
        duracion: "Día completo",
        precio: "Forfait + telecabina: 72 CHF adulto",
        temporada: ["invierno", "verano"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren + bus desde Lausana hasta Les Diablerets (1h45) o desde Aigle.",
        consejos: [
          "El Peak Walk (puente colgante entre dos cumbres) no tiene coste extra.",
          "En verano el glaciar ofrece esquí de verano y actividades familiares.",
          "Combina bien con una noche en el encantador pueblo de Les Diablerets.",
        ],
        cercaDe: "Les Diablerets, 0 km",
        keywords: ["glacier 3000 diablerets precio", "esqui vaud suiza", "peak walk suiza puente"],
      },
      {
        slug: "lausana-olimpismo",
        nombre: "Lausana: Catedral y Museo Olímpico",
        tipo: "cultura",
        descripcion: "La capital olímpica mundial con su impresionante catedral gótica y el museo del olimpismo junto al lago Lemán.",
        dificultad: "facil",
        duracion: "Día completo",
        precio: "Museo Olímpico: 18 CHF adulto",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1474537341486-989e325e6d32?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Lausana desde Ginebra (45 min) o Zúrich (2h15).",
        consejos: [
          "El metro de Lausana (M2) es el único metro suizo automático sin conductor.",
          "La catedral de Lausana es única en Europa: tiene guardián nocturno que da las horas.",
          "El paseo lacustre desde Ouchy hasta el museo olímpico es relajante y gratuito.",
        ],
        cercaDe: "Lausana, centro",
        keywords: ["lausana museo olimpico precio", "catedral lausana visita", "olimpismo lausana suiza"],
      },
    ],
  },

  // ── GINEBRA ──────────────────────────────────────────────────────────────
  {
    slug: "ginebra",
    nombre: "Ginebra",
    region: "francesa",
    descripcion: "La ciudad internacional de la diplomacia con el famoso Jet d'Eau, el lago Lemán y la Ginebra histórica del barrio antiguo.",
    imagen: "https://images.unsplash.com/photo-1750845372022-f4c633f433d5?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "jet-eau-paseo-leman",
        nombre: "Jet d'Eau y paseo por el lago Lemán",
        tipo: "urbano",
        descripcion: "El chorro de agua más alto del mundo (140m) es el símbolo de Ginebra. Paseo por el lago y los parques florales.",
        dificultad: "facil",
        duracion: "2-3 horas",
        precio: "Gratis",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1757584666096-59deb41f1124?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren a Ginebra Cornavin, luego tram o 15 min a pie hasta la orilla del lago.",
        consejos: [
          "El Jet d'Eau se puede ver desde varios puntos, pero la pasarela da acceso a la base.",
          "El parque de la Perle du Lac en la orilla norte es perfecto para picnic.",
          "Las flores del Horloge Fleurie (reloj de flores) florecen de mayo a octubre.",
          "En agosto el festival de fuegos artificiales ilumina el lago.",
        ],
        cercaDe: "Ginebra, centro",
        keywords: ["jet d'eau ginebra visita", "lago leman ginebra paseo", "que ver ginebra suiza"],
      },
      {
        slug: "vieille-ville-ginebra",
        nombre: "Vieille Ville y Catedral de Saint-Pierre",
        tipo: "cultura",
        descripcion: "El barrio histórico de Ginebra con la catedral calvnista donde predicó Juan Calvino y el museo de la Reforma.",
        dificultad: "facil",
        duracion: "3 horas",
        precio: "Gratis (torres catedral: 5 CHF)",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1555993539-1732b0258235?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Desde la estación Cornavin, tram línea 12 o 15 min a pie cuesta arriba hasta la colina de la catedral.",
        consejos: [
          "Las torres de la catedral dan la mejor vista panorámica de Ginebra.",
          "El Museo de la Reforma es gratuito los primeros domingos de mes.",
          "El barrio de la Vieille Ville tiene calles medievales y restaurantes de fondue.",
        ],
        cercaDe: "Ginebra, centro histórico",
        keywords: ["catedral saint pierre ginebra", "barrio antiguo ginebra visita", "museo reforma ginebra"],
      },
      {
        slug: "barco-leman-yvoire",
        nombre: "Barco al pueblo medieval de Yvoire (Francia)",
        tipo: "lago",
        descripcion: "Crucero por el lago Lemán hasta el encantador pueblo medieval de Yvoire en Francia, a solo 30 min en barco.",
        dificultad: "facil",
        duracion: "Día completo",
        precio: "Barco: ~35 CHF ida/vuelta",
        temporada: ["primavera", "verano", "otono"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Embarcadero CGN junto al Jet d'Eau (Jardin Anglais) en Ginebra.",
        consejos: [
          "Necesitas pasaporte o DNI para cruzar a Francia.",
          "Yvoire tiene jardín medieval (Jardín de los 5 Sentidos) y restaurantes de pescado.",
          "En temporada alta el barco está incluido en el Swiss Travel Pass (verificar CGN).",
        ],
        cercaDe: "Ginebra, embarcadero centro",
        keywords: ["yvoire barco ginebra", "lago leman excursion barco", "ginebra yvoire precio"],
      },
    ],
  },

  // ── LUCERNA ──────────────────────────────────────────────────────────────
  {
    slug: "lucerna",
    nombre: "Lucerna",
    region: "alemana",
    descripcion: "La ciudad más turística de Suiza con el Puente de la Capilla, el lago de los Cuatro Cantones y acceso al Pilatus y Rigi.",
    imagen: "https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "monte-pilatus",
        nombre: "Monte Pilatus (2.132m) — La montaña del dragón",
        tipo: "teleferico",
        descripcion: "Telecabina y cremallera más empinada del mundo (48°) hasta la cumbre con vistas panorámicas a los Alpes centrales.",
        dificultad: "facil",
        duracion: "Día completo",
        precio: "Circuito dorado: 73 CHF adulto (Swiss Travel Pass 50%)",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1669155285300-54c957706be8?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Barco desde Lucerna hasta Alpnachstad (1,5h), cremallera hasta la cumbre. Bajada en telecabina por Kriens.",
        consejos: [
          "El circuito dorado (barco + cremallera + telecabina) es la experiencia completa.",
          "La cremallera del Pilatus es la más empinada del mundo: sensación única.",
          "Con Swiss Travel Pass el barco está incluido y la cremallera al 50%.",
          "Reserva con antelación: en verano hay filas de hasta 2h para el barco.",
        ],
        cercaDe: "Lucerna, 15 km",
        keywords: ["pilatus lucerna precio teleférico", "cremallera pilatus suiza", "circuito dorado lucerna"],
      },
      {
        slug: "monte-rigi-reina",
        nombre: "Monte Rigi (1.797m) — La Reina de las Montañas",
        tipo: "teleferico",
        descripcion: "El primer cremallera de Europa (1871) hasta la cima con vistas a 13 lagos y las montañas alpinas.",
        dificultad: "facil",
        duracion: "Día completo",
        precio: "Rigi Bahnen: 58 CHF ida/vuelta (Swiss Travel Pass 50%)",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1639662696488-e0cd7deeec39?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Barco desde Lucerna hasta Vitznau (1h), cremallera hasta Rigi Kulm. O desde Weggis por telecabina.",
        consejos: [
          "El amanecer desde el Rigi es legendario: muchos turistas se quedan a dormir.",
          "En invierno hay pistas de trineo y esquí para familias.",
          "El Rigi-Kulm Hotel permite hacer noche y ver el amanecer sobre las nubes.",
        ],
        cercaDe: "Lucerna, barco 1h",
        keywords: ["monte rigi lucerna precio", "rigi kremallera primera europa", "amanecer rigi suiza"],
      },
      {
        slug: "puente-capilla-lucerna",
        nombre: "Lucerna: Puente de la Capilla y casco antiguo",
        tipo: "cultura",
        descripcion: "El puente de madera más antiguo de Europa (1333) con las murallas medievales y la plaza del Mercado.",
        dificultad: "facil",
        duracion: "3 horas",
        precio: "Gratis",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1749195403421-b40b0ff3cae7?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren a Lucerna desde Zúrich (1h) o Interlaken (2h). El puente está a 5 min a pie de la estación.",
        consejos: [
          "El puente tiene pinturas del siglo XVII sobre la vida y la muerte.",
          "La Torre del Agua (Wasserturm) junto al puente es uno de los símbolos de la ciudad.",
          "El Carnaval de Lucerna en febrero es uno de los más animados de Suiza.",
        ],
        cercaDe: "Lucerna, centro",
        keywords: ["puente capilla lucerna visita", "lucerna casco antiguo turismo", "kapellbrücke lucerna"],
      },
      {
        slug: "titlis-engelberg",
        nombre: "Titlis (3.020m) — Glaciar y teleférico giratorio",
        tipo: "teleferico",
        descripcion: "El único teleférico giratorio del mundo sube al glaciar Titlis, donde hay cueva de hielo y el puente colgante más alto de Europa.",
        dificultad: "facil",
        duracion: "Día completo",
        precio: "96 CHF adulto (Swiss Travel Pass 50%)",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1482784160316-6eb046863ece?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren desde Lucerna hasta Engelberg (1h), luego telecabinas hasta la cumbre.",
        consejos: [
          "El Rotair (teleférico giratorio 360°) da vuelta completa en 5 min.",
          "La cueva de hielo y el Cliff Walk (pasarela sobre el precipicio) están incluidos.",
          "Engleberg es también un buen pueblo para esquí familiar en invierno.",
        ],
        cercaDe: "Engelberg, 0 km",
        keywords: ["titlis engelberg teleférico precio", "glaciar titlis suiza", "teleférico giratorio suiza"],
      },
    ],
  },

  // ── BASILEA-CIUDAD ────────────────────────────────────────────────────────
  {
    slug: "basilea-ciudad",
    nombre: "Basilea-Ciudad",
    region: "alemana",
    descripcion: "La capital cultural de Suiza con el mayor museo de arte del país, el río Rin donde bañarse en verano y el carnaval más famoso de Suiza.",
    imagen: "https://images.unsplash.com/photo-1657123843551-3417f3057d2c?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "kunstmuseum-basilea",
        nombre: "Kunstmuseum Basel — el mayor museo de arte de Suiza",
        tipo: "cultura",
        descripcion: "La colección de arte más importante de Suiza con obras de Holbein, Picasso, Cézanne y contemporáneos.",
        dificultad: "facil",
        duracion: "3-4 horas",
        precio: "26 CHF adulto",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1774514580599-c3dae376348e?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren a Basilea SBB, luego tram línea 2 o 15 min a pie. El museo está junto al Steinenberg.",
        consejos: [
          "El primer domingo del mes la entrada es gratuita.",
          "La colección de Holbein el Joven es única en el mundo.",
          "El nuevo edificio (Kunstmuseum Neubau) tiene las exposiciones temporales más importantes.",
        ],
        cercaDe: "Basilea, centro",
        keywords: ["kunstmuseum basilea precio entradas", "arte suiza museo basilea", "holbein basilea museo"],
      },
      {
        slug: "bano-rin-basilea",
        nombre: "Bañarse en el Rin con los basileenses",
        tipo: "lago",
        descripcion: "La tradición veraniega de Basilea: nadar con la corriente del Rin usando una bolsa estanca para la ropa (Wickelfisch).",
        dificultad: "facil",
        duracion: "2-3 horas",
        precio: "Gratis (Wickelfisch: 15 CHF)",
        temporada: ["verano"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tram hasta Johanniterbrücke o Mittlere Brücke. El río está a 5 min de cualquier punto del centro.",
        consejos: [
          "El Wickelfisch (bolsa estanca en forma de pez) sirve de flotador y porta-ropa.",
          "Entra por el Oberer Rheinweg y sal por el Unterer Rheinweg (800m corriente abajo).",
          "Solo apto para buenos nadadores: la corriente puede ser fuerte.",
          "Muchos bares y Badi (piscinas fluviales) en ambas orillas del río.",
        ],
        cercaDe: "Basilea, centro",
        keywords: ["bañarse rin basilea verano", "wickelfisch basilea", "rin basilea turismo"],
      },
      {
        slug: "carnaval-basilea",
        nombre: "Fasnacht — El Carnaval de Basilea",
        tipo: "cultura",
        descripcion: "El mayor y más peculiar carnaval de Suiza: 3 días de máscaras, cliques musicales y linternas mágicas en la oscuridad.",
        dificultad: "facil",
        duracion: "3 días (mediados de febrero)",
        precio: "Gratis (asistencia), alojamiento muy caro en esas fechas",
        temporada: ["invierno"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren a Basilea SBB. Empieza a las 4 AM del lunes: el Morgestraich (apagado de luces y salida de cliques).",
        consejos: [
          "Reserva alojamiento con 6 meses de antelación: la ciudad se llena.",
          "El Morgestraich (lunes 4 AM) es el momento más impresionante: ciudad a oscuras.",
          "Las Waggis (personajes con nariz roja) lanzan caramelos y naranjas al público.",
          "Es Patrimonio Cultural Inmaterial de la UNESCO.",
        ],
        cercaDe: "Basilea, toda la ciudad",
        keywords: ["carnaval basilea fasnacht", "fasnacht suiza carnival", "basilea carnaval fechas"],
      },
    ],
  },

  // ── FRIBURGO ──────────────────────────────────────────────────────────────
  {
    slug: "friburgo",
    nombre: "Friburgo",
    region: "francesa",
    descripcion: "La ciudad bilingüe frontera entre Suiza alemana y francesa, con una de las mejores catedrales góticas de Europa y la cuna de la fondue.",
    imagen: "https://images.unsplash.com/photo-1488085061387-422e29b40080?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "catedral-friburgo-fondue",
        nombre: "Catedral de San Nicolás y casco medieval",
        tipo: "cultura",
        descripcion: "Una de las catedrales góticas más bellas de Suiza con vistas desde la torre sobre el río Saane y la ciudad medieval.",
        dificultad: "facil",
        duracion: "3-4 horas",
        precio: "Gratis (torre: 3 CHF)",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1746591948888-7cc1e170c17b?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren desde Berna (30 min) o Lausana (1h). A pie desde la estación (15 min).",
        consejos: [
          "Friburgo es ciudad bilingüe: el alemán y el francés conviven en las mismas calles.",
          "El barrio bajo (Basse Ville) con el río es perfecto para pasear.",
          "La fondue fribourgeoise (con gruyère) es la original: pruébala en los restaurantes locales.",
        ],
        cercaDe: "Friburgo, centro",
        keywords: ["catedral friburgo suiza visita", "fribourg suiza turismo", "fondue fribourgeoise"],
      },
      {
        slug: "lac-de-la-gruyere",
        nombre: "Lac de la Gruyère y Château de Gruyères",
        tipo: "lago",
        descripcion: "Lago artificial rodeado de prados y el pueblo medieval de Gruyères, famoso por su queso y el château.",
        dificultad: "facil",
        duracion: "Día completo",
        precio: "Château: 12 CHF adulto",
        temporada: ["primavera", "verano", "otono"],
        destacado: false,
        imagen: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Broc o Gruyères desde Friburgo (45 min). Autobús local desde la estación.",
        consejos: [
          "La fábrica de queso Gruyère en Pringy tiene visitas con cata incluida.",
          "El château medieval tiene exposiciones de arte fantástico (H.R. Giger Museum).",
          "El lago permite kayak y paddleboard en verano.",
        ],
        cercaDe: "Gruyères, 30 km desde Friburgo",
        keywords: ["gruyeres castillo suiza visita", "queso gruyere fabrica visita", "lago gruyere excursion"],
      },
    ],
  },

  // ── NEUCHÂTEL ────────────────────────────────────────────────────────────
  {
    slug: "neuchatel",
    nombre: "Neuchâtel",
    region: "francesa",
    descripcion: "Ciudad lacustre con un castillo medieval que domina el lago de Neuchâtel, la segunda ciudad universitaria de la Suiza francesa.",
    imagen: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "lago-neuchatel-barco",
        nombre: "Lago de Neuchâtel y ruta de los Tres Lagos",
        tipo: "lago",
        descripcion: "El lago más grande completamente suizo, con cruceros panorámicos y conexión fluvial con los lagos de Biel y Murten.",
        dificultad: "facil",
        duracion: "Medio día",
        precio: "Swiss Travel Pass incluido",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Neuchâtel desde Berna (45 min) o Lausana (50 min). Embarcadero junto a la estación.",
        consejos: [
          "La ruta de los 3 Lagos conecta Neuchâtel, Biel y Murten en barco.",
          "Murten (Morat) es un bonito pueblo amurallado a orillas del lago.",
          "El vino blanco de Neuchâtel (Oeil de Perdrix) es uno de los mejores de Suiza.",
        ],
        cercaDe: "Neuchâtel, centro",
        keywords: ["lago neuchatel barco excursion", "tres lagos suiza ruta", "neuchatel turismo"],
      },
    ],
  },

  // ── JURA ─────────────────────────────────────────────────────────────────
  {
    slug: "jura",
    nombre: "Jura",
    region: "francesa",
    descripcion: "El cantón más joven de Suiza (1979), con paisajes de mesetas, caballos Franches-Montagnes y rutas de senderismo poco transitadas.",
    imagen: "https://images.unsplash.com/photo-1490682143684-14369e18dce8?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "franches-montagnes-caballos",
        nombre: "Franches-Montagnes — Turismo ecuestre",
        tipo: "naturaleza",
        descripcion: "Los altiplanicies donde nació la raza de caballos Franches-Montagnes, perfectas para senderismo y equitación.",
        dificultad: "facil",
        duracion: "Día completo",
        precio: "Rutas ecuestres desde 50 CHF/h",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1490682143684-14369e18dce8?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Saignelégier desde Biel/Bienne (1h) o desde La Chaux-de-Fonds (45 min).",
        consejos: [
          "El Marché-Concours en Saignelégier (agosto) es la feria de caballos más famosa de Suiza.",
          "Las rutas de senderismo están muy bien señalizadas y son tranquilas.",
          "Ideal para escaparse del turismo masivo: el Jura es el cantón menos visitado.",
        ],
        cercaDe: "Saignelégier, centro",
        keywords: ["jura suiza turismo equitacion", "franches-montagnes caballos suiza", "saignelegier excursion"],
      },
    ],
  },

  // ── URI ───────────────────────────────────────────────────────────────────
  {
    slug: "uri",
    nombre: "Uri",
    region: "alemana",
    descripcion: "El corazón histórico de la Confederación Suiza, con la ruta original de Guillermo Tell, el lago de Uri y el paso del San Gotardo.",
    imagen: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "ruta-guillermo-tell",
        nombre: "Ruta de Guillermo Tell — Lago de Uri",
        tipo: "senderismo",
        descripcion: "Sigue los pasos del héroe suizo por las orillas del lago de Uri desde Flüelen hasta Sisikon, con el barco histórico.",
        dificultad: "moderada",
        duracion: "Día completo",
        precio: "Swiss Travel Pass incluido (barco)",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Flüelen (conexión en Arth-Goldau), barco por el lago de Uri.",
        consejos: [
          "El barco de paletas del lago de los 4 Cantones es uno de los más bonitos de Suiza.",
          "La Capilla de Tell en Sisikon marca el lugar donde, según la leyenda, saltó de la barca.",
          "Con Swiss Travel Pass el barco está completamente incluido.",
        ],
        cercaDe: "Flüelen, inicio",
        keywords: ["guillermo tell ruta suiza", "lago uri senderismo barco", "uri suiza historia turismo"],
      },
    ],
  },

  // ── SCHWYZ ────────────────────────────────────────────────────────────────
  {
    slug: "schwyz",
    nombre: "Schwyz",
    region: "alemana",
    descripcion: "El cantón que da nombre a Suiza, con los Mythen y el lago de Lauerz. Aquí se firmó el Pacto Original de la Confederación en 1291.",
    imagen: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "mythen-hike",
        nombre: "Grosser Mythen (1.899m) — El símbolo del cantón",
        tipo: "senderismo",
        descripcion: "Ascensión al pico más icónico del cantón de Schwyz con vistas a los Lagos de los 4 Cantones y los Alpes.",
        dificultad: "dificil",
        duracion: "5-6 horas",
        distancia: "10 km",
        desnivel: "+900m",
        precio: "Gratis",
        temporada: ["verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1458668383970-8ddd3927deed?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Bus desde Schwyz hasta Haggenegg. Schwyz en tren desde Arth-Goldau o Zúrich (1h).",
        consejos: [
          "El último tramo es por roca sólida con cadenas de seguridad.",
          "No recomendable para principiantes o con miedo a las alturas.",
          "Las vistas de la cumbre son 360°: uno de los mejores panoramas de Suiza central.",
        ],
        cercaDe: "Schwyz, 10 km",
        keywords: ["grosser mythen schwyz senderismo", "mythen cima suiza", "schwyz rutas montaña"],
      },
    ],
  },

  // ── ZUG ──────────────────────────────────────────────────────────────────
  {
    slug: "zug",
    nombre: "Zug",
    region: "alemana",
    descripcion: "El cantón más rico de Suiza con el pintoresco lago de Zug y la ciudad medieval. Famoso por su tarta de cereza (Zuger Kirschtorte).",
    imagen: "https://images.unsplash.com/photo-1665945203723-d823de195bf4?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "lago-zug-paseo",
        nombre: "Lago de Zug y casco histórico",
        tipo: "lago",
        descripcion: "Paseo por las orillas del lago de Zug y el casco histórico medieval con la Torre del Reloj y las murallas.",
        dificultad: "facil",
        duracion: "2-3 horas",
        precio: "Gratis",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1665945203723-d823de195bf4?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren directo desde Zúrich en 25 min. La ciudad está a 5 min de la estación.",
        consejos: [
          "La Zuger Kirschtorte (tarta de cereza con kirsch) es el postre local por excelencia.",
          "El lago de Zug tiene zonas de baño públicas gratuitas en verano.",
          "La Torre del Reloj (Zytturm) da campanadas especiales cada hora.",
        ],
        cercaDe: "Zug, centro",
        keywords: ["zug suiza visita turismo", "lago zug suiza", "zug tarta cereza"],
      },
    ],
  },

  // ── GLARIS ────────────────────────────────────────────────────────────────
  {
    slug: "glaris",
    nombre: "Glaris",
    region: "alemana",
    descripcion: "El cantón más pequeño de Suiza continental, con la democracia directa más antigua del mundo (Landsgemeinde) y paisajes alpinos vírgenes.",
    imagen: "https://images.unsplash.com/photo-1482784160316-6eb046863ece?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "klontalersee",
        nombre: "Lago Klöntal — El lago escondido de Glaris",
        tipo: "lago",
        descripcion: "Lago alpino poco conocido rodeado de prados y cascadas, accesible en coche o bicicleta desde Glarus.",
        dificultad: "facil",
        duracion: "Medio día",
        precio: "Gratis",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Glarus desde Zúrich (1h15), luego bus hasta el lago o bicicleta (9 km).",
        consejos: [
          "El lago apenas aparece en guías turísticas: tranquilidad garantizada.",
          "Hay zona de pícnic y baño permitido en verano.",
          "La carretera que bordea el lago acaba en un circo glaciar impresionante.",
        ],
        cercaDe: "Glarus, 9 km",
        keywords: ["lago klontal glaris suiza", "glarus lago excursion", "glaris turismo alpino"],
      },
    ],
  },

  // ── SOLEURA ───────────────────────────────────────────────────────────────
  {
    slug: "soleura",
    nombre: "Soleura",
    region: "alemana",
    descripcion: "La ciudad del número 11 con la catedral más bella de Suiza y el río Aare. Conocida como la ciudad más barroca del país.",
    imagen: "https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "catedral-san-ursus-soleura",
        nombre: "Catedral de San Ursus y casco histórico",
        tipo: "cultura",
        descripcion: "La catedral barroca más bella de Suiza con 11 altares, 11 campanas y 11 escalones (el 11 es sagrado en Soleura).",
        dificultad: "facil",
        duracion: "2-3 horas",
        precio: "Gratis",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1503249023995-51b0f3778ccf?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren desde Berna (35 min) o Basilea (50 min) hasta Solothurn.",
        consejos: [
          "Todo en Soleura viene en grupos de 11: el número tiene significado histórico.",
          "El Río Aare a su paso por la ciudad es perfecto para bañarse en verano.",
          "El museo de arte tiene obras barrocas destacadas.",
        ],
        cercaDe: "Soleura (Solothurn), centro",
        keywords: ["catedral solothurn soleura", "soleura suiza turismo", "solothurn suiza visita"],
      },
    ],
  },

  // ── BASILEA-CAMPIÑA ──────────────────────────────────────────────────────
  {
    slug: "basilea-campina",
    nombre: "Basilea-Campiña",
    region: "alemana",
    descripcion: "El cantón que rodea Basilea-Ciudad con los viñedos del Sundgau, castillos medievales y el pueblo termal de Liestal.",
    imagen: "https://images.unsplash.com/photo-1503249023995-51b0f3778ccf?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "augst-augusta-raurica",
        nombre: "Augusta Raurica — Las ruinas romanas mejor conservadas del norte de los Alpes",
        tipo: "cultura",
        descripcion: "La ciudad romana fundada en 44 a.C. con anfiteatro, templos y museo romano con el mayor tesoro de plata romano hallado.",
        dificultad: "facil",
        duracion: "3-4 horas",
        precio: "Museo: 12 CHF (ruinas gratuitas)",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1555993539-1732b0258235?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren desde Basilea hasta Kaiseraugst (15 min), luego 10 min a pie.",
        consejos: [
          "El anfiteatro romano acoge espectáculos de teatro en verano.",
          "El museo alberga el mayor tesoro de plata romano encontrado.",
          "Las ruinas están al aire libre: acceso gratuito incluso cuando el museo está cerrado.",
        ],
        cercaDe: "Basilea, 10 km",
        keywords: ["augusta raurica ruinas romanas suiza", "augst basilea ruinas", "anfiteatro romano suiza"],
      },
    ],
  },

  // ── SCHAFFHAUSEN ─────────────────────────────────────────────────────────
  {
    slug: "schaffhausen",
    nombre: "Schaffhausen",
    region: "alemana",
    descripcion: "Hogar de las Cataratas del Rin, las más grandes de Europa central, y una de las ciudades medievales mejor conservadas de Suiza.",
    imagen: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "cataratas-rin",
        nombre: "Cataratas del Rin — Las más grandes de Europa",
        tipo: "naturaleza",
        descripcion: "Las cataratas más grandes de Europa central (150m de ancho, 23m de caída) con visitas en barco a la roca central.",
        dificultad: "facil",
        duracion: "2-3 horas",
        precio: "Barco a la roca central: 7 CHF. Plataformas: gratis",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Schaffhausen (45 min desde Zúrich), bus hasta Neuhausen am Rheinfall (10 min).",
        consejos: [
          "En mayo/junio el caudal es máximo: el espectáculo más impresionante.",
          "El barco hasta la roca central del río es la experiencia estrella.",
          "El Castillo Laufen ofrece las mejores vistas desde la orilla sur.",
          "Gratuito aparcar en Neuhausen: evita el parking de pago junto a las cataratas.",
        ],
        cercaDe: "Schaffhausen, 3 km",
        keywords: ["cataratas rin precio visita", "cascadas rin suiza", "rheinfall schaffhausen excursion"],
      },
    ],
  },

  // ── APPENZELL RODAS EXTERIORES ────────────────────────────────────────────
  {
    slug: "appenzell-exterior",
    nombre: "Appenzell Rodas Exteriores",
    region: "alemana",
    descripcion: "El cantón que rodea a Appenzell Interior, con el pico Säntis y las tradiciones alpinas más antiguas de Suiza.",
    imagen: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "santis-teleférico",
        nombre: "Säntis (2.502m) — El pico de los Alpes de Appenzell",
        tipo: "teleferico",
        descripcion: "Teleférico hasta la cumbre del Säntis con vistas a los lagos del Bodensee y los seis países que se divisan en días claros.",
        dificultad: "facil",
        duracion: "Medio día",
        precio: "50 CHF ida/vuelta (Swiss Travel Pass 50%)",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1708991872571-c5f7db8ea2da?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Bus desde Urnäsch o Appenzell hasta Schwägalp (estación del teleférico). Desde Zúrich ~1,5h.",
        consejos: [
          "En días claros se ven Alemania, Austria, Francia, Liechtenstein, Italia y el lago de Constanza.",
          "La estación meteorológica en la cumbre es una de las más importantes de Suiza.",
          "El sendero de bajada por Meglisalp (2h) es espectacular pero requiere forma física.",
        ],
        cercaDe: "Urnäsch, 10 km",
        keywords: ["santis teleférico precio appenzell", "santis cumbre suiza", "schwägalp teleférico"],
      },
    ],
  },

  // ── APPENZELL RODAS INTERIORES ────────────────────────────────────────────
  {
    slug: "appenzell-interior",
    nombre: "Appenzell Rodas Interiores",
    region: "alemana",
    descripcion: "El cantón más pequeño de Suiza y el último que concedió el voto a la mujer (1990). Famoso por sus tradiciones, bordados y queso.",
    imagen: "https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "pueblo-appenzell",
        nombre: "Pueblo de Appenzell y Landsgemeinde",
        tipo: "cultura",
        descripcion: "El pueblo más tradicional de Suiza con casas de colores, bordados regionales y la famosa asamblea democrática al aire libre.",
        dificultad: "facil",
        duracion: "3-4 horas",
        precio: "Gratis",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren desde Gossau o St. Gallen (1h desde Zúrich, cambio en Gossau/Herisau).",
        consejos: [
          "La Landsgemeinde (votación a mano alzada al aire libre) es cada último domingo de abril.",
          "El queso Appenzeller es uno de los más aromáticos de Suiza: visita la fábrica.",
          "El museo de bordados y costumbres regionales está en el centro del pueblo.",
        ],
        cercaDe: "Appenzell, centro",
        keywords: ["appenzell pueblo suiza visita", "landsgemeinde democracia directa suiza", "queso appenzeller visita"],
      },
    ],
  },

  // ── SAN GALO ──────────────────────────────────────────────────────────────
  {
    slug: "san-galo",
    nombre: "San Galo",
    region: "alemana",
    descripcion: "La ciudad del lino y el bordado, con la abadía de St. Gallen (Patrimonio UNESCO) y su biblioteca barroca considerada la más bella del mundo.",
    imagen: "https://images.unsplash.com/photo-1552325225-59770dcc3a69?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "biblioteca-abadia-san-galo",
        nombre: "Biblioteca de la Abadía de St. Gallen (UNESCO)",
        tipo: "cultura",
        descripcion: "Considerada la biblioteca barroca más bella del mundo, con más de 170.000 volúmenes y manuscritos del siglo VIII.",
        dificultad: "facil",
        duracion: "2 horas",
        precio: "13 CHF adulto",
        temporada: ["primavera", "verano", "otono", "invierno"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1762928289094-197055a5d5c3?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren desde Zúrich hasta St. Gallen (1h). La abadía está a 10 min a pie de la estación.",
        consejos: [
          "Solo se puede visitar con zapatillas de fieltro para proteger el parquet.",
          "Los libros más antiguos datan del siglo VIII: únicos en Europa.",
          "La catedral adyacente tiene una de las criptas románicas más bonitas de Suiza.",
        ],
        cercaDe: "St. Gallen, centro",
        keywords: ["biblioteca san galo patrimonio", "stiftsbibliothek st gallen precio", "abadia san galo visita"],
      },
    ],
  },

  // ── ARGOVIA ──────────────────────────────────────────────────────────────
  {
    slug: "argovia",
    nombre: "Argovia",
    region: "alemana",
    descripcion: "El cantón de los castillos (más de 200), los Habsburgo y el río Aare con termas naturales en Schinznach-Bad.",
    imagen: "https://images.unsplash.com/photo-1568883654012-283591d1e9b8?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "castillo-habsburg",
        nombre: "Castillo Habsburg — La cuna de los emperadores",
        tipo: "cultura",
        descripcion: "El castillo que da nombre a la dinastía que gobernó Europa durante siglos, en una colina sobre el río Aare.",
        dificultad: "facil",
        duracion: "2-3 horas",
        precio: "5 CHF adulto",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1488085061387-422e29b40080?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Bus desde Brugg (10 min). Brugg en tren desde Zúrich (35 min) o Berna (50 min).",
        consejos: [
          "El sendero de 2 km desde Brugg hasta el castillo es fácil y agradable.",
          "La dinastía Habsburg gobernó el Sacro Imperio Romano desde aquí.",
          "El Cantón Argovia tiene la mayor densidad de castillos de Suiza.",
        ],
        cercaDe: "Brugg, 3 km",
        keywords: ["castillo habsburg argovia visita", "habsburgo castillo suiza", "argovia castillos medievales"],
      },
    ],
  },

  // ── TURGOVIA ──────────────────────────────────────────────────────────────
  {
    slug: "turgovia",
    nombre: "Turgovia",
    region: "alemana",
    descripcion: "El cantón de los manzanos y el lago de Constanza. Las orillas del Bodensee son perfectas para ciclismo y deportes acuáticos.",
    imagen: "https://images.unsplash.com/photo-1553532434-5ab5b6b84993?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "lago-constanza-ciclovía",
        nombre: "Ciclismo por las orillas del lago de Constanza",
        tipo: "naturaleza",
        descripcion: "La ruta ciclista del Bodensee (273 km totales) recorre las orillas del lago a través de Suiza, Alemania y Austria.",
        dificultad: "facil",
        duracion: "Día completo (tramo suizo: 50 km)",
        precio: "Alquiler bici: 30-40 CHF/día",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1565098772267-60af42b81ef2?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Kreuzlingen o Konstanz desde Zúrich (1h). Las bicis se alquilan en la estación.",
        consejos: [
          "La ruta es plana y apta para toda la familia.",
          "Konstanz (Alemania) está justo al lado: fácil cruzar la frontera en bici.",
          "En verano hay ferries que cruzan el lago y permiten hacer circuitos.",
        ],
        cercaDe: "Kreuzlingen, orilla del lago",
        keywords: ["lago constanza ciclismo bodensee", "kreuzlingen suiza turismo", "bodensee bicicleta suiza"],
      },
    ],
  },

  // ── OBWALDEN ──────────────────────────────────────────────────────────────
  {
    slug: "obwalden",
    nombre: "Obwalden",
    region: "alemana",
    descripcion: "Pequeño cantón en el corazón de los Alpes con el Monte Pilatus en su frontera y el lago Sarner, perfecto para retiros tranquilos.",
    imagen: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "lago-sarnen-engstlen",
        nombre: "Lago Engstlen y Tannensee — Los lagos azules de Obwalden",
        tipo: "lago",
        descripcion: "Dos lagos alpinos de color turquesa intenso en las montañas de Obwalden, accesibles por un bonito sendero.",
        dificultad: "moderada",
        duracion: "5-6 horas",
        distancia: "12 km",
        precio: "Gratis",
        temporada: ["verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Bus desde Meiringen hasta Engstlenalp (verano), luego a pie. Meiringen en tren desde Interlaken.",
        consejos: [
          "El hotel-restaurante en Engstlenalp permite hacer noche en medio de las montañas.",
          "El sendero entre ambos lagos es de bajo nivel técnico.",
          "Muy poca afluencia de visitantes: tranquilidad alpina garantizada.",
        ],
        cercaDe: "Meiringen, 20 km",
        keywords: ["engstlensee obwalden lago suiza", "tannensee suiza senderismo", "obwalden excursion lagos"],
      },
    ],
  },

  // ── NIDWALDEN ─────────────────────────────────────────────────────────────
  {
    slug: "nidwalden",
    nombre: "Nidwalden",
    region: "alemana",
    descripcion: "El cantón hermano de Obwalden con acceso al lago de los Cuatro Cantones, el Stanserhorn y la ciudad de Stans.",
    imagen: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=85&auto=format&fit=crop",
    actividades: [
      {
        slug: "stanserhorn-cabriolet",
        nombre: "Stanserhorn (1.898m) — El teleférico cabriolet",
        tipo: "teleferico",
        descripcion: "El único teleférico de dos pisos con techo abierto del mundo sube en 6 min hasta una cumbre con vistas al lago y los Alpes.",
        dificultad: "facil",
        duracion: "Medio día",
        precio: "58 CHF ida/vuelta (Swiss Travel Pass 50%)",
        temporada: ["primavera", "verano", "otono"],
        destacado: true,
        imagen: "https://images.unsplash.com/photo-1613002999602-9e59d2c3cbfc?w=1200&q=85&auto=format&fit=crop",
        comoLlegar: "Tren hasta Stans desde Luzern (20 min), luego funicular + telecabina.",
        consejos: [
          "El CabriO es único en el mundo: piso superior descubierto para sentir el viento.",
          "La cumbre tiene restaurante giratorio con menú regional.",
          "La antigua cremallera (1893) aún funciona como museum piece.",
        ],
        cercaDe: "Stans, 0 km",
        keywords: ["stanserhorn teleférico cabriolet precio", "cabriolet suiza teleférico abierto", "stans nidwalden"],
      },
    ],
  },
];

export { cantones };
